.catalog:
  name: simplehttpserver
  version: 0
  description: Yet another simple http server but written by golang.
  uuid: simplehttpserver-0
  questions:
  - variable: "HTTP_LISTEN_PORT"
    label: "HTTP_LISTEN_PORT"
    description: "Specify an available port to listen."
    default: 9091
    required: true
    type: "int"
  - variable: "LOG_PATH"
    label: "LOG_PATH"
    description: "Specify an local path to storage the logs."
    default: "/data/simplehttpserver/simplehttpserver"
    required: true
    type: "string"
  - variable: "DEPLOY_ON"
    label: "DEPLOY_ON"
    description: "Specify a host to deploy this stack."
    default: ""
    required: true
    type: "string"

simplehttpserver:
  scale: 1