.catalog:
  name: simplehttpserver
  version: 1
  description: Yet another simple http server but written by golang.
  uuid: simplehttpserver-1
  questions:
  - variable: "LISTEN_PORT"
    label: "LISTEN_PORT"
    description: "Specify an available port to listen."
    default: 888
    required: true
    type: "int"
  - variable: "RESPONSE"
    label: "RESPONSE"
    description: "http reponse"
    default: "hello world!"
    required: false
    type: "string"

node:
  scale: 1