.catalog:
  name: ngxlog
  version: 2
  description: Yufanjiasu Ngxlog System.
  uuid: ngxlog-2
  questions:
  - variable: TRANSFER_LISTEN_PORT
    label: "TRANSFER_LISTEN_PORT"
    description: "Specify an available port to listen for Transfer."
    default: 8100
    required: true
    type: "int"
  - variable: LOG_PATH
    label: "LOG_PATH"
    description: "Specify an local path to storage the ngx log."
    default: "/data/ngx_log_server/"
    required: true
    type: "string"
  - variable: NGX_LOG_SERVER
    label: "NGX_LOG_SERVER"
    description: "Specify a collection of NgxLogServer hosts to deploy the services."
    default: s1
    required: true
    type: enum
    options:
      - s0
      - s1
      - s2
  - variable: "ENABLED_LOG_UPLOAD"
    label: "ENABLED_LOG_UPLOAD"
    description: "Enabled log upload to Aliyun OSS."     
    required: true
    default: 1 
    type: "enum"
    options:
      - 0
      - 1
  

conf:
  scale: 1
  start_on_create: true

transfer:
  scale: 1
  start_on_create: true

loguper:
  scale: ${ENABLED_LOG_UPLOAD}
  start_on_create: true