node:
  image: hub.yfcloud.com/simplehttpserver:latest
  environment:
    LISTEN_PORT: ${LISTEN_PORT}
    RESPONSE: ${RESPONSE}
  ports:
    - 8081:${LISTEN_PORT}/tcp
  tty: true
  volumes:
    - ${WORKING_DIR}