version: '2'

services:
  conf:
    image: hub.yfcloud.com/ngxlog/conf:latest
    network_mode: none
    tty: true
    stdin_open: true

  loguper:
    depends_on:
      - conf
    image: hub.yfcloud.com/ngxlog/loguper:latest
    network_mode: host
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - "/var/docker/ngxlog/loguper/var/:/ngxlog/loguper/var/"
      - "${LOG_PATH}:${LOG_PATH}"
    volumes_from:
      - conf
    command:
      - -c=/ngxlog/conf/loguper.yml
    labels:
      io.rancher.sidekicks: conf
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: ngxlogserver=s1

  transfer:
    depends_on:
      - conf
    image: hub.yfcloud.com/ngxlog/transfer:latest
    network_mode: host
    ports:
      - "${TRANSFER_LISTEN_PORT}:8100"
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - "/var/docker/ngxlog/transfer/var/:/ngxlog/transfer/var/"
      - "/etc/hosts:/etc/hosts"
      - "${LOG_PATH}:${LOG_PATH}"
    volumes_from:
      - conf
    command:
      - -c=/ngxlog/conf/transfer.yml
    labels:
      io.rancher.scheduler.affinity:host_label: ngxlogserver=${NGX_LOG_SERVER}
      io.rancher.sidekicks: conf
      io.rancher.container.pull_image: always

